# Generated by Django 2.2.16 on 2023-02-08 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20230208_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='counts',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='counts',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=200, verbose_name='Мера измерения'),
        ),
    ]
