# Generated by Django 2.2.16 on 2023-02-08 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_auto_20230208_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='counts',
        ),
        migrations.AddField(
            model_name='ingredientinrecipe',
            name='counts',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
