# Generated by Django 2.2.16 on 2023-02-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0006_auto_20230208_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='counts',
            new_name='amount',
        ),
    ]
